services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: edudb
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/app
      - ./media:/app/media
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduuser -d edudb"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    # Добавляем команду createsuperuser с флагом --noinput
    command: >
      sh -c "python manage.py makemigrations api &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput || true &&
             python manage.py seed_db &&
             python manage.py runserver 0.0.0.0:7600"
    volumes:
      - .:/app
    ports:
      - "7600:7600"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://eduuser:edupassword@db:5432/edudb
      DJANGO_SECRET_KEY: "django-insecure-dev-secret-key-change-in-prod"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@mail.ru"
      DJANGO_SUPERUSER_FIRSTNAME: "Admin"
      DJANGO_SUPERUSER_LASTNAME: "System"
      DJANGO_SUPERUSER_PATRONYMIC: "Root"
      DJANGO_SUPERUSER_ROLE: "admin"

volumes:
  pgdata: