# Generated by Django 5.0.4 on 2026-04-29 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['position'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники групп'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='studentcluster',
            options={'verbose_name': 'Кластер студента', 'verbose_name_plural': 'Кластеры студентов'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результаты тестирования', 'verbose_name_plural': 'Результаты тестирований'},
        ),
        migrations.AlterModelOptions(
            name='trainingquestion',
            options={'ordering': ['position'], 'verbose_name': 'Вопрос тренажера', 'verbose_name_plural': 'Вопросы тренажера'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия тренажера', 'verbose_name_plural': 'Сессии тренажера'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='videotype',
            options={'verbose_name': 'Тип видео', 'verbose_name_plural': 'Типы видео'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='Правильно?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question', verbose_name='Связанный вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='final_test',
            field=models.OneToOneField(blank=True, help_text='Финальный тест в конце блока ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_block_of', to='api.test', verbose_name='Финальный тест блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Видимость для пользователей ', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='block',
            name='lessons_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во уроков в блоке'),
        ),
        migrations.AlterField(
            model_name='block',
            name='position',
            field=models.IntegerField(default=0, help_text='Влияет на порядок обьектов ', verbose_name='Позиция блока в уроке'),
        ),
        migrations.AlterField(
            model_name='block',
            name='subject',
            field=models.ForeignKey(help_text='Предмет, в котором находится блок', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД Группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='block',
            field=models.ForeignKey(help_text='Блок в котором находится урок ', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0, help_text='Суммарная длительность урока в секундах', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД Урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Видимость для пользователей ', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=0, help_text='Влияет на порядок обьектов ', verbose_name='Позиция урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Саммари урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, help_text='Тест в уроке ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_for', to='api.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Видеоматериал урока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.video', verbose_name='Связанное видео'),
        ),
        migrations.AlterField(
            model_name='question',
            name='recommendation_link',
            field=models.URLField(blank=True, help_text='Материал для повторения по этому вопросу', max_length=2048, null=True, verbose_name='Ссылка на текстовую рекомендацию'),
        ),
        migrations.AlterField(
            model_name='question',
            name='recommendation_video_link',
            field=models.URLField(blank=True, help_text='Материал для повторения по этому вопросу', max_length=2048, null=True, verbose_name='Ссылка на видео ресурс'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test', verbose_name='Связанный тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=0, help_text='Таймер теста в секундах (0 = без ограничений)', verbose_name='Длительность теста в сек'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ИД Теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Видимость для пользователей ', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(help_text='Название', max_length=255, verbose_name='Заголовок теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Конец в'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД Результата'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало в'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отвечено в'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_training', to='api.answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ИД Вопрсоа тренажера'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Правильность'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_questions', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_questions', to='api.trainingsession', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('correct', 'Ответ верный'), ('wrong', 'Ответ неверный'), ('skipped', 'Пропущен')], default='pending', max_length=8, verbose_name='Статус прохождения'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пройдена в'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана в'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД Сессии тренажера'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Урок, к которому относится сессия тренажёра', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='api.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='source_test_result',
            field=models.ForeignKey(blank=True, help_text='Попытка, по ошибкам которой создана сессия. null = глобальный тренажёр', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='api.testresult', verbose_name='Попытка теста'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Не начата'), ('active', 'В процессе'), ('completed', 'Завершена')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активация аккаунта пользователя', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Является ли пользователь персоналом', verbose_name='Статус персонала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отвечено в'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in', to='api.answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД ответа пользователя'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильность'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.testresult', verbose_name='ИД результата тестирования'),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ИД типа видео'),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название типа видео'),
        ),
    ]
