# Generated by Django 5.0.4 on 2026-04-29 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='api.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='api.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет группы',
                'verbose_name_plural': 'Предметы групп',
                'db_table': 'group_subjects',
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teachers', to='api.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель группы',
                'verbose_name_plural': 'Преподаватели групп',
                'db_table': 'teacher_groups',
                'unique_together': {('teacher', 'group')},
            },
        ),
    ]
