# Generated by Django 5.0.4 on 2026-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subject_creator_groupsubject_teachergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Баллы за вопрос'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='earned_points',
            field=models.IntegerField(default=0, verbose_name='Набранные баллы'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Максимальные баллы'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Получено баллов'),
        ),
    ]
