# Generated by Django 5.0.4 on 2026-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_testresult_score_question_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец в'),
        ),
    ]
