# Generated by Django 5.0.4 on 2026-05-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_test_creator_video_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, help_text='В секундах', verbose_name='Длительность видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.videotype', verbose_name='Тип видео'),
        ),
    ]
