# Generated by Django 5.0.4 on 2026-05-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_duration_alter_video_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdifficulty',
            options={'verbose_name': 'Сложность теста', 'verbose_name_plural': 'Сложность тестов'},
        ),
    ]
