# Generated by Django 5.0.4 on 2026-05-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_testdifficulty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDifficulty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10)),
                ('avg_score', models.FloatField(default=0, help_text='Процент успешных ответов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='api.question')),
            ],
            options={
                'verbose_name': 'Сложность вопроса',
                'verbose_name_plural': 'Сложности вопросов',
                'db_table': 'question_difficulties',
            },
        ),
    ]
