# Generated by Django 5.0.4 on 2026-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_questiondifficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingquestion',
            name='chosen_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='chosen_answer',
        ),
        migrations.AddField(
            model_name='trainingquestion',
            name='chosen_answers',
            field=models.ManyToManyField(blank=True, related_name='chosen_in_training', to='api.answer', verbose_name='Выбранные ответы'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='chosen_answers',
            field=models.ManyToManyField(blank=True, related_name='chosen_in', to='api.answer', verbose_name='Выбранные ответы'),
        ),
    ]
