# Generated by Django 5.0.4 on 2026-05-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_trainingquestion_chosen_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание'),
        ),
    ]
